#2
name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/#35
  pull_request:
    branches:
      - feature/#35

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Gradle
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: AWS Credentials Setup
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker image create
        run: docker build -t sss_team7:latest .

      - name: Docker image tagging
        run: docker tag sss_team7:latest ${{ secrets.AWS_ECR_REGISTRY }}/sss_team7:latest

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.AWS_ECR_REGISTRY }}/sss_team7:latest

      - name: SSH into EC2 and deploy Docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            # ECR 로그인 다시 시도
            docker login -u AWS -p $(aws ecr get-login-password --region ap-northeast-2) ${{ secrets.AWS_ECR_REGISTRY }}

            # 기존 Docker 컨테이너 중지 및 삭제
            docker stop my-new-container || true
            docker rm my-new-container || true

            # 새로운 Docker 이미지 다운로드 및 실행
            docker pull ${{ secrets.AWS_ECR_REGISTRY }}/sss_team7:latest
            docker run -d --name my-new-container ${{ secrets.AWS_ECR_REGISTRY }}/sss_team7:latest
